### ISSUE TITLE
The current directory must be a Git repository!

### ISSUE THREAD

**Issue by mjahmadi** [sohanemon/AutoCommit#2]
after click on generate button, this notification message just appears 

'The current directory must be a Git repository!'

**Comment by sohanemon** [comment]
you must initialize git repository first.

**Comment by boromyr** [comment]
@sohanemon How?

**Comment by sohanemon** [comment]
you can initialize git by running `git init`

**Comment by boromyr** [comment]
I have already tried, both in an empty folder and in an existing repo, but I always get the same error.
